ALTER TABLE agents ADD COLUMN total_votes_given BIGINT NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN follower_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN following_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN reply_count BIGINT NOT NULL DEFAULT 0;
